# Generated by Django 4.1.7 on 2023-04-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='URL',
            new_name='url',
        ),
        migrations.AddField(
            model_name='webpage',
            name='email',
            field=models.EmailField(default='cricket@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='accessrecord',
            name='date',
            field=models.DateField(),
        ),
    ]
